//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DepartmentalSurvey.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SchoolYear
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SchoolYear()
        {
            this.EvaluationPeriod = new HashSet<EvaluationPeriod>();
        }
    
        public int SchoolYearId { get; set; }
        public string SchoolYearName { get; set; }
        public bool Enabled { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public byte[] RowVersion { get; set; }
        public Nullable<System.DateTime> SurveyStart { get; set; }
        public Nullable<System.DateTime> SurveyEnd { get; set; }
        public Nullable<System.DateTime> StudentUpdateStart { get; set; }
        public Nullable<System.DateTime> StudentUpdateEnd { get; set; }
        public Nullable<bool> ForOnlineReservation { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EvaluationPeriod> EvaluationPeriod { get; set; }
    }
}
