//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DepartmentalSurvey.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SurveyItems
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SurveyItems()
        {
            this.EvaluationDetail = new HashSet<EvaluationDetail>();
        }
    
        public int ItemId { get; set; }
        public int DepartmentId { get; set; }
        public string SurveyQuestion { get; set; }
        public Nullable<int> Weight { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual Department Department { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EvaluationDetail> EvaluationDetail { get; set; }
    }
}
